run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    
  shadow:
    strict: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/akurinnoy/kubectx-manager

  # golint: deprecated, replaced by revive
  revive:
    confidence: 0.8

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  unparam:
    check-exported: false

  unused:
    check-exported: false

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used when creation file or using chmod
      - G306 # Poor file permissions used when writing to a file

  lll:
    line-length: 120

  # maligned: deprecated linter, removed

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # Don't enable:
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl
  # 
  # Deprecated/removed linters:
  # - golint (use revive instead)
  # - maligned (removed from golangci-lint)
  # - gomnd (renamed to mnd)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - mnd

    # Exclude known linters from partially hard-to-fix issues
    - path: cmd/
      linters:
        - lll
        - funlen

    # Exclude shadow checking on the variable named err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
